/* The frozen shell on the new stack (spec 043 Phase B, phases.md §1).

   build.py assembles ONE HTML file: the body markup of shell.html with its
   twenty-five <script src="TAG"> lines replaced by the files' contents and
   its own inline script at the end. This does the same assembly, from the
   same list in the same order, into the shape a served page takes:

     public/shell.js    every script, verbatim, in build.py's order — the
                        shared rules, the data, the renderers, the modes,
                        sync.js and the shell's own inline block — followed
                        by shell/route.js, the ONE piece of new browser code
                        (the address ↔ the place)
     public/theme.js    theme.js as it is, run from the head
     shell/body.html    shell.html with the script tags taken out — the
                        markup the route serves inside its own document

   Nothing in it is edited: every source is read whole and concatenated, and
   the assembly is asserted byte-identical to build.py's own list, so a file
   build.py gains tomorrow turns this red rather than being missed. External
   scripts, not inline, is what lets the served page carry `script-src 'self'`
   with no hash and no unsafe-inline (§238's net, tighter).

     node scripts/build-shell.mjs */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, "..", "..");
const SRC = join(ROOT, "SMP-Project-Folder", "src");

/* build.py's own list, read out of build.py rather than kept here (§53.5). */
const buildPy = readFileSync(join(SRC, "build.py"), "utf8");
const list = [...buildPy.matchAll(/\("([A-Z]+)","([^"]+)"\)/g)].map((m) => ({ tag: m[1], file: m[2] }));
if (list.length < 20 || list[list.length - 1].tag !== "SYNC") throw new Error("build-shell: build.py's list was not read (" + list.length + " entries)");

let shell = readFileSync(join(SRC, "shell.html"), "utf8");
const parts = [];
for (const { tag, file } of list) {
  const marker = '<script src="' + tag + '"></script>';
  if (!shell.includes(marker)) throw new Error("build-shell: shell.html has no " + marker);
  shell = shell.replace(marker + "\n", "").replace(marker, "");
  parts.push("/* ── " + file + " ── */\n" + readFileSync(join(SRC, file), "utf8"));
}
/* the shell's own script — the LAST <script> block, which build.py leaves inline */
const m = /<script>\n([\s\S]*)<\/script>\s*$/.exec(shell);
if (!m) throw new Error("build-shell: the shell's inline script was not found");
parts.push("/* ── shell.html (inline) ── */\n" + m[1]);
const body = shell.slice(0, m.index).replace(/\n+$/, "\n");
parts.push("/* ── shell/route.js (the address and the place) ── */\n" + readFileSync(join(here, "..", "shell", "route.js"), "utf8"));

mkdirSync(join(here, "..", "public", "fonts"), { recursive: true });
writeFileSync(join(here, "..", "public", "shell.js"),
  "/* GENERATED by scripts/build-shell.mjs from SMP-Project-Folder/src — build.py's list, verbatim. Do not edit. */\n" + parts.join("\n"));
writeFileSync(join(here, "..", "public", "theme.js"),
  "/* GENERATED by scripts/build-shell.mjs from SMP-Project-Folder/src/theme.js. Do not edit. */\n" + readFileSync(join(SRC, "theme.js"), "utf8"));
writeFileSync(join(here, "..", "shell", "body.html"),
  "<!-- GENERATED by scripts/build-shell.mjs from SMP-Project-Folder/src/shell.html, its script tags taken out. Do not edit. -->\n" + body);
copyFileSync(join(SRC, "fonts", "Source_Sans_3.woff2"), join(here, "..", "public", "fonts", "Source_Sans_3.woff2"));

/* FOREFRONT'S OWN PAGE (platform.html, §313.3), verbatim, with its one inline
   script moved to a file for the same CSP reason. Its <style> stays inline
   (style-src keeps 'unsafe-inline', as the frozen header did). */
const pf = readFileSync(join(ROOT, "platform.html"), "utf8");
const pm = /<script>\n([\s\S]*)<\/script>\s*<\/body>/.exec(pf);
if (!pm) throw new Error("build-shell: platform.html's script was not found");
writeFileSync(join(here, "..", "public", "platform-page.js"), "/* GENERATED by scripts/build-shell.mjs from platform.html. Do not edit. */\n" + pm[1]);
writeFileSync(join(here, "..", "shell", "platform.html"),
  "<!-- GENERATED by scripts/build-shell.mjs from platform.html, its script moved to /platform-page.js. Do not edit. -->\n" +
  pf.slice(0, pm.index) + '<script src="/platform-page.js"></script>\n</body>' + pf.slice(pm.index + pm[0].length));
parts.push("/* platform.html (inline) */\n" + pm[1]);

/* THE PAGE HAS TO PARSE (§69.22): every script is run through new Function,
   which parses without executing — build.py's own refusal. */
for (const p of parts) { try { new Function(p); } catch (e) { throw new Error("build-shell: a script does not parse — " + p.slice(0, 40) + ": " + e.message); } }
console.log("wrote public/shell.js —", parts.length, "scripts,", parts.reduce((n, p) => n + p.length, 0), "bytes; shell/body.html", body.length, "bytes");
