/* THE WORKER THAT CARRIES THE NOTIFICATIONS AND STORES NOTHING (spec 043
   Phase J, stop point C — Islam, 2026-09-10: *"1. ok"*).

   The plan says two things about this file and they were both right about
   their own half. Line 47 says **no service worker and no offline copy**,
   and it is reasoned entirely about CACHING: the frozen product was ONE
   static file, so holding it on disk was safe and §91's cache-by-name trap
   was the price. The new app's platform document is SERVER-RENDERED and
   depends on who is signed in, so a cached copy of it is not a stale shell,
   it is one person's page served to the next person on that device — worse
   than the fault the cache existed to avoid. That half of the plan stands
   and this file keeps it: NOTHING is stored, and there is no `fetch`
   handler at all, so the browser goes to the network for everything exactly
   as it would with no worker present.

   Phase G's row says **carry notifications**, and `push` lives in this one
   file — a browser cannot receive one without a registered worker, so with
   no file at this address `pushSync()` could never subscribe a device. It
   also registers BEFORE it asks whether this device wants a subscription
   (§282.4), so every page load for every viewer logged
   `A bad HTTP response code (404) was received when fetching the script.`
   — the one recorded ERROR in every sweep since Phase G, with nobody having
   turned anything on.

   So: the caching half is DROPPED and the notification half is CARRIED —
   generated from the frozen `sw.js` rather than copied, and asserted, so a
   change to the frozen push handler cannot be missed and a copy cannot
   drift a word at a time (§53.5; the discipline scripts/build-shell.mjs
   already uses on build.py's own list).

   AND IT IS WHAT CLEARS THE FROZEN CACHES (§91). A browser returning after
   the cutover holds the old worker AND its `smp-shell-*` cache. This one
   deletes EVERY cache on activate and claims its clients, so no returning
   browser can be served the frozen platform out of its own disk — which is
   §91's own failure, and the reason Phase J's row asks for a file here at
   all. It destroys the old CACHES, not itself: it stays resident, because
   staying resident is how a push arrives with no tab open.

   A side effect worth naming rather than discovering: claiming the clients
   fires `controllerchange` in a tab that already had a controller, which is
   what §258's *"A newer version of the platform is ready"* watches — so an
   open tab on the frozen build is offered the reload at the cutover instead
   of sitting on a build that no longer exists.

     node scripts/build-sw.mjs        (re-run if ../sw.js changes)
*/
import { readFileSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
/* SMP_FROZEN_SW points it at a doctored copy, so the guards below can be
   proved able to fail without moving the frozen file (§276, SMP_BUILT's
   own shape). Never read in a build; the default is the frozen worker. */
const FROZEN = process.env.SMP_FROZEN_SW || join(here, "..", "..", "sw.js");
const MARK = "/* ══ A BOX THAT ARRIVES WITH NO TAB OPEN (§231)";

const src = readFileSync(FROZEN, "utf8");
const at = src.indexOf(MARK);
if (at < 0) throw new Error("build-sw: the frozen worker no longer carries §231's marker — the notification half cannot be found, so nothing is guessed at");
const dropped = src.slice(0, at);
const carried = src.slice(at);

/* BOTH ENDS, or a build that carried the wrong half would pass (§94.2).
   What is DROPPED must really be the caching half, and what is CARRIED must
   really be the notification half and must depend on none of it. */
const must = (cond, why) => { if (!cond) throw new Error("build-sw: " + why); };
must(/const SHELL\s*=/.test(dropped), "the dropped half holds no SHELL name — is this the caching half?");
must(dropped.includes('addEventListener("fetch"'), "the dropped half holds no fetch handler — is this the caching half?");
must(dropped.includes("caches.open("), "the dropped half opens no cache — is this the caching half?");
must(carried.includes('addEventListener("push"'), "the carried half holds no push handler");
must(carried.includes('addEventListener("notificationclick"'), "the carried half holds no notificationclick handler");
must(!/caches/.test(carried), "the carried half touches `caches` — it would depend on the half being dropped");
must(!/SHELL/.test(carried), "the carried half names SHELL — it would depend on the half being dropped");
must(!/addEventListener\("fetch"/.test(carried), "the carried half holds a fetch handler — nothing here may serve from disk");

const head =
  "/* GENERATED by scripts/build-sw.mjs from the frozen sw.js. Do not edit here.\n" +
  "   Spec 043 Phase J, stop point C: the notification half of the frozen worker,\n" +
  "   carried verbatim below; the caching half dropped, because the new platform\n" +
  "   document is server-rendered and per person, so a cached copy is one\n" +
  "   person's page served to the next. This worker STORES NOTHING and has no\n" +
  "   fetch handler at all — the browser goes to the network for everything. */\n" +
  "\n" +
  "self.addEventListener(\"install\", () => self.skipWaiting());\n" +
  "\n" +
  "/* EVERY cache, not the ones this file knows the names of: what has to go is\n" +
  "   the frozen deployment's `smp-shell-*`, and a returning browser is the only\n" +
  "   place those names exist. Then claim the clients, so a tab open on the old\n" +
  "   build stops being controlled by a worker serving a platform that is no\n" +
  "   longer there (§91) — and hears about it (§258's controllerchange). */\n" +
  "self.addEventListener(\"activate\", (e) => {\n" +
  "  e.waitUntil(\n" +
  "    caches.keys()\n" +
  "      .then((ks) => Promise.all(ks.map((k) => caches.delete(k))))\n" +
  "      .then(() => self.clients.claim())\n" +
  "  );\n" +
  "});\n" +
  "\n";

mkdirSync(join(here, "..", "public"), { recursive: true });
const out = join(here, "..", "public", "sw.js");
writeFileSync(out, head + carried);
console.log("wrote public/sw.js —", statSync(out).size, "bytes;", carried.split("\n").length, "lines carried verbatim from sw.js, the caching half dropped");
