/* The settled design crosses to the new stack VERBATIM (§20). These are the
   platform's own stylesheets, concatenated in exactly the order build.py uses,
   into one file the app imports. Generated, never hand-copied: a hand-copied
   stylesheet is how a design drifts one shade at a time.

     node scripts/sync-css.mjs        (re-run if src/*.css changes)
*/
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "..", "..", "SMP-Project-Folder", "src");
const ORDER = ["_shared.css", "group-extra.css", "config.css", "arrange.css", "present.css"];

const css = ORDER.map((f) => readFileSync(join(SRC, f), "utf8")).join("\n");
const out = join(here, "..", "app", "platform.css");
writeFileSync(out,
  "/* GENERATED by scripts/sync-css.mjs from SMP-Project-Folder/src/*.css.\n" +
  "   Do not edit here — edit the source stylesheet and re-run the script. */\n" + css);
console.log("wrote app/platform.css —", css.length, "bytes from", ORDER.length, "stylesheets");
