/* The settled design crosses to the new stack VERBATIM (§20). These are the
   platform's own stylesheets, concatenated in exactly the order build.py uses,
   into one file the app imports. Generated, never hand-copied: a hand-copied
   stylesheet is how a design drifts one shade at a time.

     node scripts/sync-css.mjs        (re-run if src/*.css changes)
*/
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "..", "..", "SMP-Project-Folder", "src");
const ORDER = ["_shared.css", "group-extra.css", "config.css", "arrange.css", "present.css",
               "chat.css", "tour.css", "welcome.css", "builder.css"];

/* SERVED AS FILES, NEVER BUNDLED. The product's own CSS carries a comment
   with a stray close-comment mark in it (§272.8 records the fault and what it eats); a
   browser parses past it exactly as the frozen page does, and a bundler's
   CSS parser refuses the file outright. Verbatim (D4) means the browser
   reads the same bytes the product serves, so both sheets are written under
   public/ and linked from their route group's layout. */
/* THE TYPEFACE (build.py §157): one embedded face, Source Sans 3, which
   build.py carries as a data URI so the single file works from a memory
   stick. Served, it is a file beside the stylesheet (public/fonts, copied by
   scripts/build-shell.mjs) — the same bytes, font-display:swap for the same
   reason. */
const FACE = "@font-face{font-family:'Source Sans 3';font-style:normal;font-weight:400 800;font-display:swap;src:url(/fonts/Source_Sans_3.woff2) format('woff2')}\n";
const css = FACE + ORDER.map((f) => readFileSync(join(SRC, f), "utf8")).join("\n");
mkdirSync(join(here, "..", "public"), { recursive: true });
const out = join(here, "..", "public", "platform.css");
writeFileSync(out,
  "/* GENERATED by scripts/sync-css.mjs from SMP-Project-Folder/src/*.css.\n" +
  "   Do not edit here — edit the source stylesheet and re-run the script. */\n" + css);
console.log("wrote public/platform.css —", css.length, "bytes from", ORDER.length, "stylesheets");

/* THE DOOR'S OWN STYLESHEET (§34, §313.36): index.html's <style> block, taken
   between its tags and written beside the door's route group. The door is
   Forefront's surface with Forefront's own tokens (--gold is #F5A623 there
   and #C9A24D inside the platform), so it is loaded on the door routes ONLY
   — a route group's CSS reaches that group's routes and no other. */
const gate = readFileSync(join(here, "..", "..", "index.html"), "utf8");
const m = /<style>\n([\s\S]*?)\n<\/style>/.exec(gate);
if (!m) throw new Error("sync-css: index.html has no <style> block");
const doorOut = join(here, "..", "public", "door.css");
writeFileSync(doorOut,
  "/* GENERATED from index.html's own <style> block by scripts/sync-css.mjs — the\n" +
  "   door's stylesheet, carried verbatim (D4, §20). Edit index.html, re-run. */\n" + m[1] + "\n");
console.log("wrote public/door.css —", m[1].length, "bytes from index.html");
