  onlineshop: {
    name: "Online Shop", codePrefix: "OS", weight: 0, real: false,
    clauses: [
      ["We are", "Raya Trade's owned online storefront"],
      ["We sell", "consumer electronics, mobiles, IT and accessories"],
      ["To", "individual consumers across Egypt"],
      ["Through", "web, app and marketplace listings"],
      ["Covering", "all governorates via the group's logistics network"],
      ["Using", "group inventory and shared last-mile capacity"],
    ],
    aspiration: "By the end of 2027: to be the first destination Egyptians open when they shop electronics online — fastest to deliver, widest assortment, and the easiest returns in the market.",
    keyObjectives: [
      { name: "Online revenue", dir: "≥", target3y: "2.6B EGP", target: "1.8B EGP", compile: "Sum", actual: "1.1B", progress: 61 },
      { name: "Site conversion rate", dir: "≥", target3y: "3.2%", target: "2.4%", compile: "Latest", actual: "1.8%", progress: 75 },
      { name: "Repeat purchase rate", dir: "≥", target3y: "40%", target: "28%", compile: "Latest", actual: "19%", progress: 68 },
      { name: "Assortment breadth (live SKUs)", dir: "≥", target3y: "24,000", target: "14,000", compile: "Latest", actual: "9,400", progress: 67 },
    ],
    swot: {
      s: ["Owned traffic and first-party data", "Access to full group assortment"],
      w: ["Thin margins after delivery cost", "Brand awareness behind pure-play rivals"],
      o: ["Marketplace expansion", "Subscription-based delivery"],
      t: ["Aggressive discounting by pure-plays", "Rising paid-acquisition cost"],
    },
    items: [
      { code: "OS01", name: "Assortment & Availability", sub: "",
        kind: "Direction", theme: "OT", owner: "Sherif Adel",
        measures: [
          { name: "Live SKU count", dir: "≥", target: "14,000", compile: "Latest", actual: "9,400", progress: 67 },
          { name: "Out-of-stock rate", dir: "≤", target: "4%", compile: "Latest", actual: "7%", progress: 57 },
          { name: "Supplier lead time", dir: "≤", target: "10 d", compile: "Latest", actual: "14 d", progress: 71 },
        ],
        tactics: [
          { name: "Onboard group assortment to storefront", owner: "Sherif Adel", s: 1, e: 3, status: "WIP", actual: 55, planned: 67 },
          { name: "Automated stock sync with warehouses", owner: "Nadia Fouad", s: 2, e: 4, status: "WIP", actual: 40, planned: 33 },
          { name: "Third-party seller pilot", owner: "Sherif Adel", s: 3, e: 4, status: "WIP", actual: 25, planned: 33 },
        ] },
      { code: "OS02", name: "Conversion & Retention", sub: "",
        kind: "Direction", theme: "VC", owner: "Nadia Fouad",
        measures: [
          { name: "Conversion rate", dir: "≥", target: "2.4%", compile: "Latest", actual: "1.8%", progress: 75 },
          { name: "Cart abandonment", dir: "≤", target: "62%", compile: "Latest", actual: "71%", progress: 87 },
          { name: "App install base", dir: "≥", target: "900,000", compile: "Latest", actual: "540,000", progress: 60 },
        ],
        tactics: [
          { name: "Checkout redesign and one-tap pay", owner: "Nadia Fouad", s: 1, e: 2, status: "WIP", actual: 80, planned: 100 },
          { name: "Loyalty programme launch", owner: "Sherif Adel", s: 2, e: 4, status: "WIP", actual: 45, planned: 33 },
          { name: "Personalised recommendation engine", owner: "Nadia Fouad", s: 3, e: 4, status: "WIP", actual: 30, planned: 33 },
        ] },
    ] },
  consumerelectronics: {
    name: "Consumer Electronics", codePrefix: "CE", weight: 0, real: false,
    clauses: [
      ["We are", "the group's consumer electronics distribution arm"],
      ["We provide", "value-added distribution and channel development"],
      ["For", "brand principals, retail chains and independent dealers"],
      ["Through", "a national dealer network and key-account teams"],
      ["Covering", "Egypt, with selected export lines"],
      ["Using", "group logistics, credit facilities and after-sales"],
    ],
    aspiration: "By the end of 2027: to be the distributor every major appliance and electronics brand chooses first for Egypt, with the deepest retail coverage in the category.",
    keyObjectives: [
      { name: "CE distribution revenue", dir: "≥", target3y: "7.8B EGP", target: "5.4B EGP", compile: "Sum", actual: "2.4B", progress: 44 },
      { name: "CE market share", dir: "≥", target3y: "24%", target: "18%", compile: "Latest", actual: "14%", progress: 78 },
      { name: "Active dealer accounts", dir: "≥", target3y: "2,600", target: "1,900", compile: "Latest", actual: "1,410", progress: 74 },
      { name: "Gross margin", dir: "≥", target3y: "9.5%", target: "8.2%", compile: "Latest", actual: "7.1%", progress: 87 },
    ],
    swot: {
      s: ["Long-standing principal relationships", "National dealer coverage"],
      w: ["Heavy working-capital requirement", "Exposure to a few large brands"],
      o: ["Premium appliance segment growth", "Own-label accessories"],
      t: ["Direct-to-retail moves by principals", "Currency volatility on imports"],
    },
    items: [
      { code: "CE01", name: "Brand Portfolio Depth", sub: "",
        kind: "Direction", theme: "DIV", owner: "Tarek Nassar",
        measures: [
          { name: "Principal agreements signed", dir: "≥", target: "4", compile: "Sum", actual: "2", progress: 50 },
          { name: "Revenue from top-2 brands", dir: "≤", target: "55%", compile: "Latest", actual: "64%", progress: 86 },
          { name: "New category revenue", dir: "≥", target: "900M EGP", compile: "Sum", actual: "310M", progress: 34 },
        ],
        tactics: [
          { name: "Negotiate two additional principal lines", owner: "Tarek Nassar", s: 1, e: 3, status: "WIP", actual: 50, planned: 67 },
          { name: "Own-label accessory range", owner: "Heba Salem", s: 2, e: 4, status: "WIP", actual: 35, planned: 33 },
          { name: "Premium segment entry plan", owner: "Tarek Nassar", s: 2, e: 4, status: "WIP", actual: 45, planned: 33 },
        ] },
      { code: "CE02", name: "Dealer Network Development", sub: "",
        kind: "Direction", theme: "OT", owner: "Heba Salem",
        measures: [
          { name: "Active dealers", dir: "≥", target: "1,900", compile: "Latest", actual: "1,410", progress: 74 },
          { name: "Dealer credit utilisation", dir: "≥", target: "70%", compile: "Latest", actual: "52%", progress: 74 },
          { name: "Dealer churn", dir: "≤", target: "8%", compile: "Latest", actual: "12%", progress: 67 },
        ],
        tactics: [
          { name: "Tiered dealer incentive scheme", owner: "Heba Salem", s: 1, e: 4, status: "WIP", actual: 60, planned: 50 },
          { name: "Regional dealer service hubs", owner: "Tarek Nassar", s: 2, e: 4, status: "WIP", actual: 38, planned: 33 },
          { name: "Dealer portal rollout", owner: "Heba Salem", s: 3, e: 4, status: "WIP", actual: 28, planned: 33 },
        ] },
    ] },
  corporate: {
    name: "Corporate", codePrefix: "CO", weight: 0, real: false,
    clauses: [
      ["We are", "the group's enterprise and government sales arm"],
      ["We provide", "end-to-end technology supply, integration and support contracts"],
      ["For", "large enterprises, banks, telcos and government entities"],
      ["Through", "direct key-account teams and tender participation"],
      ["Covering", "Egypt"],
      ["Using", "group product access, IT services and financing capacity"],
    ],
    aspiration: "By the end of 2027: to be the single technology supply partner for Egypt's largest enterprises and government programmes, selling solutions rather than boxes.",
    keyObjectives: [
      { name: "Corporate revenue", dir: "≥", target3y: "1.4B EGP", target: "0.9B EGP", compile: "Sum", actual: "0.42B", progress: 47 },
      { name: "Contracted recurring revenue", dir: "≥", target3y: "260M EGP", target: "150M EGP", compile: "Sum", actual: "61M", progress: 41 },
      { name: "Tender win rate", dir: "≥", target3y: "35%", target: "26%", compile: "Latest", actual: "19%", progress: 73 },
      { name: "Named enterprise accounts", dir: "≥", target3y: "140", target: "95", compile: "Latest", actual: "72", progress: 76 },
    ],
    swot: {
      s: ["Breadth of product access across the group", "Established government references"],
      w: ["Long cash-conversion cycles", "Thin technical pre-sales bench"],
      o: ["Public digitisation programmes", "Managed-service contracts"],
      t: ["Global integrators entering tenders", "Budget deferrals in public sector"],
    },
    items: [
      { code: "CO01", name: "Solution Selling Capability", sub: "",
        kind: "Capability", theme: "VC", owner: "Amr Bakr",
        measures: [
          { name: "Certified pre-sales engineers", dir: "≥", target: "18", compile: "Latest", actual: "11", progress: 61 },
          { name: "Solution-led deal share", dir: "≥", target: "45%", compile: "Latest", actual: "29%", progress: 64 },
          { name: "Average deal size", dir: "≥", target: "3.2M EGP", compile: "Latest", actual: "2.1M", progress: 66 },
        ],
        tactics: [
          { name: "Pre-sales academy and certification", owner: "Amr Bakr", s: 1, e: 4, status: "WIP", actual: 55, planned: 50 },
          { name: "Reference architecture library", owner: "Laila Zaki", s: 2, e: 3, status: "WIP", actual: 60, planned: 67 },
          { name: "Vendor solution partnerships", owner: "Amr Bakr", s: 2, e: 4, status: "WIP", actual: 42, planned: 33 },
        ] },
      { code: "CO02", name: "Public Sector Programmes", sub: "",
        kind: "Direction", theme: "DIV", owner: "Laila Zaki",
        measures: [
          { name: "Active public contracts", dir: "≥", target: "24", compile: "Latest", actual: "16", progress: 67 },
          { name: "Tender win rate", dir: "≥", target: "26%", compile: "Latest", actual: "19%", progress: 73 },
          { name: "Public revenue", dir: "≥", target: "420M EGP", compile: "Sum", actual: "178M", progress: 42 },
        ],
        tactics: [
          { name: "Framework agreement registrations", owner: "Laila Zaki", s: 1, e: 3, status: "WIP", actual: 70, planned: 67 },
          { name: "Dedicated bid desk", owner: "Amr Bakr", s: 2, e: 4, status: "WIP", actual: 45, planned: 33 },
          { name: "Compliance and certification programme", owner: "Laila Zaki", s: 3, e: 4, status: "WIP", actual: 30, planned: 33 },
        ] },
    ] },
  care: {
    name: "Care", codePrefix: "CA", weight: 0, real: false,
    clauses: [
      ["We are", "the group's after-sales and service organisation"],
      ["We provide", "authorised repair, warranty administration and extended service plans"],
      ["For", "brand principals, group business units and end customers"],
      ["Through", "service centres, pick-up points and on-site teams"],
      ["Covering", "Egypt"],
      ["Using", "certified technicians, parts inventory and the group's logistics network"],
    ],
    aspiration: "By the end of 2027: to be the after-sales operation brands trust with their reputation — the reason a customer buys the second device from us.",
    keyObjectives: [
      { name: "Service revenue", dir: "≥", target3y: "1.3B EGP", target: "0.9B EGP", compile: "Sum", actual: "0.44B", progress: 49 },
      { name: "First-time fix rate", dir: "≥", target3y: "92%", target: "86%", compile: "Latest", actual: "78%", progress: 91 },
      { name: "Average turnaround time", dir: "≤", target3y: "3 d", target: "4 d", compile: "Latest", actual: "6 d", progress: 67 },
      { name: "Extended plan attach rate", dir: "≥", target3y: "22%", target: "15%", compile: "Latest", actual: "9%", progress: 60 },
    ],
    swot: {
      s: ["Authorised status with major brands", "National service footprint"],
      w: ["Parts availability drives turnaround", "Technician attrition"],
      o: ["Extended warranty as a margin pool", "Service for third-party retailers"],
      t: ["Brands insourcing service", "Grey-market repair pricing"],
    },
    items: [
      { code: "CA01", name: "Service Excellence", sub: "",
        kind: "Capability", theme: "OT", owner: "Mostafa Deif",
        measures: [
          { name: "First-time fix rate", dir: "≥", target: "86%", compile: "Latest", actual: "78%", progress: 91 },
          { name: "Turnaround time", dir: "≤", target: "4 d", compile: "Latest", actual: "6 d", progress: 67 },
          { name: "Customer satisfaction", dir: "≥", target: "4.5", compile: "Latest", actual: "4.0", progress: 89 },
        ],
        tactics: [
          { name: "Parts availability programme", owner: "Mostafa Deif", s: 1, e: 3, status: "WIP", actual: 65, planned: 67 },
          { name: "Technician certification ladder", owner: "Rania Fahmy", s: 1, e: 4, status: "WIP", actual: 50, planned: 50 },
          { name: "Service tracking for customers", owner: "Mostafa Deif", s: 2, e: 4, status: "WIP", actual: 40, planned: 33 },
        ] },
      { code: "CA02", name: "Service Revenue Growth", sub: "",
        kind: "Direction", theme: "DIV", owner: "Rania Fahmy",
        measures: [
          { name: "Extended plan attach rate", dir: "≥", target: "15%", compile: "Latest", actual: "9%", progress: 60 },
          { name: "Third-party service revenue", dir: "≥", target: "180M EGP", compile: "Sum", actual: "62M", progress: 34 },
          { name: "Out-of-warranty revenue", dir: "≥", target: "240M EGP", compile: "Sum", actual: "112M", progress: 47 },
        ],
        tactics: [
          { name: "Extended plan sales at point of sale", owner: "Rania Fahmy", s: 1, e: 4, status: "WIP", actual: 48, planned: 50 },
          { name: "Third-party retailer service contracts", owner: "Mostafa Deif", s: 2, e: 4, status: "WIP", actual: 35, planned: 33 },
          { name: "Service pricing review", owner: "Rania Fahmy", s: 2, e: 3, status: "WIP", actual: 70, planned: 67 },
        ] },
    ] },
  it: {
    name: "IT", codePrefix: "IT", weight: 0, real: false,
    clauses: [
      ["We are", "the group's IT products and infrastructure distributor"],
      ["We provide", "distribution, configuration and infrastructure services"],
      ["For", "resellers, system integrators and corporate buyers"],
      ["Through", "a reseller network and direct infrastructure teams"],
      ["Covering", "Egypt"],
      ["Using", "vendor authorisations, technical staff and group logistics"],
    ],
    aspiration: "By the end of 2027: to be the leading distributor of IT products and infrastructure in Egypt, with services attached to every major hardware line we carry.",
    keyObjectives: [
      { name: "IT distribution revenue", dir: "≥", target3y: "3.4B EGP", target: "2.2B EGP", compile: "Sum", actual: "0.98B", progress: 45 },
      { name: "Services attach rate", dir: "≥", target3y: "28%", target: "18%", compile: "Latest", actual: "11%", progress: 61 },
      { name: "Active reseller accounts", dir: "≥", target3y: "900", target: "640", compile: "Latest", actual: "471", progress: 74 },
      { name: "Inventory turns", dir: "≥", target3y: "7.0", target: "5.5", compile: "Latest", actual: "4.2", progress: 76 },
    ],
    swot: {
      s: ["Vendor authorisations across major lines", "Technical configuration capability"],
      w: ["Price-led reseller relationships", "Obsolescence risk on stock"],
      o: ["Cloud and infrastructure services", "Refurbished hardware line"],
      t: ["Vendor direct-to-reseller programmes", "Import duty changes"],
    },
    items: [
      { code: "IT01", name: "Reseller Channel Growth", sub: "",
        kind: "Direction", theme: "OT", owner: "Yasser Kamal",
        measures: [
          { name: "Active resellers", dir: "≥", target: "640", compile: "Latest", actual: "471", progress: 74 },
          { name: "Revenue per reseller", dir: "≥", target: "3.4M EGP", compile: "Latest", actual: "2.1M", progress: 62 },
          { name: "Reseller portal adoption", dir: "≥", target: "70%", compile: "Latest", actual: "44%", progress: 63 },
        ],
        tactics: [
          { name: "Reseller tiering and rebate scheme", owner: "Yasser Kamal", s: 1, e: 4, status: "WIP", actual: 58, planned: 50 },
          { name: "Self-service ordering portal", owner: "Dina Shawky", s: 2, e: 4, status: "WIP", actual: 42, planned: 33 },
          { name: "Regional reseller events", owner: "Yasser Kamal", s: 2, e: 3, status: "WIP", actual: 65, planned: 67 },
        ] },
      { code: "IT02", name: "Infrastructure Services", sub: "",
        kind: "Direction", theme: "VC", owner: "Dina Shawky",
        measures: [
          { name: "Services revenue", dir: "≥", target: "400M EGP", compile: "Sum", actual: "178M", progress: 45 },
          { name: "Services attach rate", dir: "≥", target: "18%", compile: "Latest", actual: "11%", progress: 61 },
          { name: "Certified engineers", dir: "≥", target: "24", compile: "Latest", actual: "15", progress: 63 },
        ],
        tactics: [
          { name: "Managed infrastructure offering", owner: "Dina Shawky", s: 1, e: 4, status: "WIP", actual: 45, planned: 50 },
          { name: "Engineer certification programme", owner: "Yasser Kamal", s: 1, e: 3, status: "WIP", actual: 62, planned: 67 },
          { name: "Cloud partner accreditation", owner: "Dina Shawky", s: 3, e: 4, status: "WIP", actual: 28, planned: 33 },
        ] },
    ] },
  logistics: {
    name: "Logistics", codePrefix: "LG", weight: 0, real: false,
    clauses: [
      ["We are", "the group's logistics and fulfilment operation"],
      ["We provide", "warehousing, line-haul, last-mile delivery and cash collection"],
      ["For", "group business units and external e-commerce and retail clients"],
      ["Through", "hubs, spokes and a contracted fleet"],
      ["Covering", "all governorates of Egypt"],
      ["Using", "owned warehousing, routing systems and a managed courier network"],
    ],
    aspiration: "By the end of 2027: to be a profitable third-party logistics business in its own right, not merely the group's internal delivery arm.",
    keyObjectives: [
      { name: "Logistics revenue", dir: "≥", target3y: "2.4B EGP", target: "1.6B EGP", compile: "Sum", actual: "0.71B", progress: 44 },
      { name: "External client revenue share", dir: "≥", target3y: "45%", target: "30%", compile: "Latest", actual: "18%", progress: 60 },
      { name: "On-time delivery rate", dir: "≥", target3y: "96%", target: "92%", compile: "Latest", actual: "86%", progress: 93 },
      { name: "Cost per parcel", dir: "≤", target3y: "28 EGP", target: "33 EGP", compile: "Latest", actual: "39 EGP", progress: 85 },
    ],
    swot: {
      s: ["National hub-and-spoke coverage", "Captive group volume as a base load"],
      w: ["Fleet largely contracted, not owned", "Cash-on-delivery reconciliation burden"],
      o: ["Third-party e-commerce fulfilment", "Cross-border into Nigeria"],
      t: ["Well-funded courier startups", "Fuel and fleet cost inflation"],
    },
    items: [
      { code: "LG01", name: "Network Efficiency", sub: "",
        kind: "Capability", theme: "OT", owner: "Hazem Roushdy",
        measures: [
          { name: "On-time delivery", dir: "≥", target: "92%", compile: "Latest", actual: "86%", progress: 93 },
          { name: "Cost per parcel", dir: "≤", target: "33 EGP", compile: "Latest", actual: "39 EGP", progress: 85 },
          { name: "Hub utilisation", dir: "≥", target: "82%", compile: "Latest", actual: "68%", progress: 83 },
        ],
        tactics: [
          { name: "Route optimisation system", owner: "Hazem Roushdy", s: 1, e: 3, status: "WIP", actual: 72, planned: 67 },
          { name: "Hub capacity rebalancing", owner: "Mai Sobhy", s: 2, e: 4, status: "WIP", actual: 44, planned: 33 },
          { name: "Returns handling redesign", owner: "Hazem Roushdy", s: 2, e: 4, status: "WIP", actual: 38, planned: 33 },
        ] },
      { code: "LG02", name: "Third-Party Client Growth", sub: "",
        kind: "Direction", theme: "DIV", owner: "Mai Sobhy",
        measures: [
          { name: "External client revenue", dir: "≥", target: "480M EGP", compile: "Sum", actual: "192M", progress: 40 },
          { name: "Named 3PL clients", dir: "≥", target: "40", compile: "Latest", actual: "23", progress: 58 },
          { name: "Client retention", dir: "≥", target: "85%", compile: "Latest", actual: "74%", progress: 87 },
        ],
        tactics: [
          { name: "3PL commercial proposition and pricing", owner: "Mai Sobhy", s: 1, e: 3, status: "WIP", actual: 68, planned: 67 },
          { name: "Client onboarding and SLA framework", owner: "Hazem Roushdy", s: 2, e: 4, status: "WIP", actual: 40, planned: 33 },
          { name: "Fulfilment-as-a-service pilot", owner: "Mai Sobhy", s: 3, e: 4, status: "WIP", actual: 26, planned: 33 },
        ] },
    ] },
  nigeria: {
    name: "Nigeria", codePrefix: "NG", weight: 0, real: false,
    clauses: [
      ["We are", "the group's Nigerian distribution operation"],
      ["We provide", "mobile and consumer electronics distribution and retail supply"],
      ["For", "local retail chains, independent dealers and operators"],
      ["Through", "a Lagos hub and regional dealer partners"],
      ["Covering", "Nigeria, focused on Lagos, Abuja and Port Harcourt"],
      ["Using", "group brand relationships and an asset-light local structure"],
    ],
    aspiration: "By the end of 2027: to have proven the group's distribution model outside Egypt, with Nigeria standing on its own commercially and ready to be repeated elsewhere.",
    keyObjectives: [
      { name: "Nigeria revenue", dir: "≥", target3y: "2.2B EGP", target: "1.1B EGP", compile: "Sum", actual: "0.38B", progress: 35 },
      { name: "Local dealer accounts", dir: "≥", target3y: "420", target: "240", compile: "Latest", actual: "138", progress: 58 },
      { name: "Contribution margin", dir: "≥", target3y: "6.0%", target: "4.2%", compile: "Latest", actual: "2.6%", progress: 62 },
      { name: "Working capital cycle", dir: "≤", target3y: "55 d", target: "70 d", compile: "Latest", actual: "91 d", progress: 77 },
    ],
    swot: {
      s: ["Group brand relationships transfer", "Asset-light entry keeps risk contained"],
      w: ["Thin local management bench", "Limited local credit history"],
      o: ["Large underserved dealer base", "Second market as a repeatable template"],
      t: ["Currency convertibility and repatriation", "Regulatory and import unpredictability"],
    },
    items: [
      { code: "NG01", name: "Market Establishment", sub: "",
        kind: "Direction", theme: "DIV", owner: "Chidi Okafor",
        measures: [
          { name: "Dealer accounts", dir: "≥", target: "240", compile: "Latest", actual: "138", progress: 58 },
          { name: "Cities covered", dir: "≥", target: "6", compile: "Latest", actual: "3", progress: 50 },
          { name: "Brand lines carried", dir: "≥", target: "5", compile: "Latest", actual: "3", progress: 60 },
        ],
        tactics: [
          { name: "Lagos hub and warehousing", owner: "Chidi Okafor", s: 1, e: 2, status: "WIP", actual: 85, planned: 100 },
          { name: "Regional dealer recruitment", owner: "Amaka Eze", s: 1, e: 4, status: "WIP", actual: 52, planned: 50 },
          { name: "Local brand agreements", owner: "Chidi Okafor", s: 2, e: 4, status: "WIP", actual: 40, planned: 33 },
        ] },
      { code: "NG02", name: "Commercial Viability", sub: "",
        kind: "Direction", theme: "VC", owner: "Amaka Eze",
        measures: [
          { name: "Contribution margin", dir: "≥", target: "4.2%", compile: "Latest", actual: "2.6%", progress: 62 },
          { name: "Working capital cycle", dir: "≤", target: "70 d", compile: "Latest", actual: "91 d", progress: 77 },
          { name: "Overhead ratio", dir: "≤", target: "9%", compile: "Latest", actual: "13%", progress: 69 },
        ],
        tactics: [
          { name: "Local credit and collections policy", owner: "Amaka Eze", s: 1, e: 3, status: "WIP", actual: 60, planned: 67 },
          { name: "Cost base review", owner: "Chidi Okafor", s: 2, e: 4, status: "WIP", actual: 44, planned: 33 },
          { name: "Repatriation and FX hedging plan", owner: "Amaka Eze", s: 2, e: 4, status: "WIP", actual: 36, planned: 33 },
        ] },
    ] },
