/* ── Templates ────────────────────────────────────────────────────────────
   Two templates, one file per unit.

   PLAN carries the whole authored strategy — foundation clauses, the winning
   aspiration, the key objectives with both horizons, and every pillar with its
   measures and tactics. It carries no actuals: a plan states what was
   committed to.

   PROGRESS carries only what is reported — an actual against each measure and
   a percent complete against each tactic. It cannot create anything, and it
   cannot change a target.

   Every row carries the item's id. That is what lets the same file be uploaded
   twice without duplicating a plan, and what lets a diff say "this target
   changed" rather than "this measure is new".
   ──────────────────────────────────────────────────────────────────────── */

/* The column contract follows the deck-extraction template the strategy team
   already produces, so a file they build for a deck loads without reshaping.
   Three columns are added to it:
     value_3y      the three-year target beside this year's
     collaborators everyone on a tactic who is not the owner
     end_in_mind   carried as its own ASPIRATION row, as the source file does
   ────────────────────────────────────────────────────────────────────── */

var PLAN_COLS = ["id","type","parent_id","source_slide","name","description","outcome",
                 "owner","collaborators","direction","value","value_3y","unit","horizon",
                 "compile","q1","q2","q3","q4","theme","kind","notes"];
/* The progress template mirrors the plan template's shape rather than
   inventing a second vocabulary: same ids, same types, same direction and
   unit columns. It adds `current` and `new_value`, and covers NORTHSTAR as
   well as measures and tactics \u2014 the unit's headline is its Key Objectives,
   so leaving them out made the one number the page is built on unreportable. */
var PROG_COLS = ["id","type","parent_id","parent_name","name","direction",
                 "value","unit","compile","current","new_value","notes"];

function csvCell(v){
  v = v == null ? "" : String(v);
  return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
}
function csvRow(cols, o){ return cols.map(function(c){ return csvCell(o[c]); }).join(","); }

/* A target is held as one string. The template splits it into a number and a
   unit, which is how the source file carries it and the only form arithmetic
   can use. Anything unparseable travels whole in `value`. */
function splitTarget(s){
  if (s == null) return { value:"", unit:"" };
  var m = String(s).trim().match(/^(-?[\d.,]+)\s*(.*)$/);
  return m ? { value:m[1], unit:m[2] } : { value:String(s), unit:"" };
}
/* Rebuilding a target from its parts must give back the original spacing:
   "6.2B EGP" splits to 6.2 and "B EGP" and has to rejoin without a space,
   while "24 h" has to keep one. The separator is read from what is stored
   rather than guessed from the unit. */
function joinTarget(original, value, unit){
  value = (value == null ? "" : String(value)).trim();
  unit  = (unit  == null ? "" : String(unit)).trim();
  if (!value) return "";
  var m = String(original == null ? "" : original).match(/^(-?[\d.,]+)(\s*)(.*)$/);
  var sep = m ? m[2] : (unit && unit.length > 1 && /^[A-Za-z]/.test(unit) ? " " : "");
  return unit ? value + sep + unit : value;
}
/* Compared part by part, so a difference in spacing is never reported as a
   changed target. */
function targetChanged(stored, value, unit){
  var a = splitTarget(stored);
  return a.value !== String(value == null ? "" : value).trim() ||
         a.unit  !== String(unit  == null ? "" : unit).trim();
}

function planTemplate(u){
  var rows = [PLAN_COLS.join(",")];
  /* Provenance is stored on whatever it arrived with and written back, so a
     round trip through the platform does not destroy which slide a row
     came from. */
  var slide = function(id){ var h = findById(u, id); return h && h.obj ? (h.obj.slide || "") : ""; };
  rows.push(csvRow(PLAN_COLS, { id:u.ukey + "-PLAN", type:"PLAN", name:u.name + " strategic plan",
    horizon:GROUP.horizon, notes:"Generated by the platform" }));
  /* One row, six clauses piped in order \u2014 the shape the strategy team's
     extraction produces, so a file leaving the platform is the same shape as
     one arriving. The labels lead each part, as they do in the source. */
  rows.push(csvRow(PLAN_COLS, { id:u.clauses[0] ? u.clauses[0][2] : u.ukey + "-F1",
    type:"FOUNDATION", source_slide:u.slideOf ? u.slideOf.foundation : "",
    name:"Strategic foundation (Who we are)",
    description:u.clauses.map(function(c){ return c[0] + " " + c[1]; }).join(" | "),
    notes:"Labelled lines in source order: " + u.clauses.map(function(c){ return c[0]; }).join(" | ") }));
  rows.push(csvRow(PLAN_COLS, { id:u.ukey + "-ASP1", type:"ASPIRATION", name:"Winning aspiration",
    description:u.aspiration, horizon:GROUP.horizon, source_slide:slide(u.ukey + "-ASP1") }));
  rows.push(csvRow(PLAN_COLS, { id:u.ukey + "-ASP2", type:"ASPIRATION", name:"End in mind",
    description:u.endInMind, source_slide:slide(u.ukey + "-ASP2") }));
  u.keyObjectives.forEach(function(m){
    var a = splitTarget(m.target), b = splitTarget(m.target3y);
    rows.push(csvRow(PLAN_COLS, { id:m.id, type:"NORTHSTAR", name:m.name, direction:m.dir,
      value:a.value, value_3y:b.value, unit:a.unit, compile:m.compile,
      source_slide:m.slide, horizon:m.horizon, notes:m.notes }));
  });
  [["s","STRENGTH"],["w","WEAKNESS"],["o","OPPORTUNITY"],["t","THREAT"]].forEach(function(pair){
    (u.swot[pair[0]] || []).forEach(function(x, i){
      rows.push(csvRow(PLAN_COLS, { id:u.ukey + "-" + pair[1][0] + (i+1), type:pair[1], name:x,
        source_slide:slide(u.ukey + "-" + pair[1][0] + (i+1)) }));
    });
  });
  u.items.forEach(function(p, pi){
    rows.push(csvRow(PLAN_COLS, { id:p.id, type:"PILLAR", name:p.name, kind:p.kind,
      theme:p.theme, owner:p.owner, source_slide:p.slide,
      notes:p.notes || (p.kind + " " + pillarCode(u, pi).replace(/^\D+/, "")) }));
    p.measures.forEach(function(m){
      var a = splitTarget(m.target);
      rows.push(csvRow(PLAN_COLS, { id:m.id, type:"MEASURE", parent_id:p.id, name:m.name,
        direction:m.dir, value:a.value, unit:a.unit, compile:m.compile,
        source_slide:m.slide, horizon:m.horizon, notes:m.notes }));
    });
    p.tactics.forEach(function(t){
      rows.push(csvRow(PLAN_COLS, { id:t.id, type:"TACTIC", parent_id:p.id, name:t.name,
        description:t.description, outcome:t.outcome, owner:t.owner,
        collaborators:(t.collaborators || []).join("|"),
        q1:t.q1 ? 1 : 0, q2:t.q2 ? 1 : 0, q3:t.q3 ? 1 : 0, q4:t.q4 ? 1 : 0,
        source_slide:t.slide, notes:t.notes }));
    });
  });
  return rows.join("\n");
}

function progressTemplate(u){
  var rows = [PROG_COLS.join(",")];
  u.keyObjectives.forEach(function(m){
    var a = splitTarget(m.target);
    rows.push(csvRow(PROG_COLS, { id:m.id, type:"NORTHSTAR", parent_name:u.name, name:m.name,
      direction:m.dir, value:a.value, unit:a.unit, compile:m.compile,
      current:m.actual, new_value:"",
      notes:m.target ? "" : "no target set \u2014 recorded, not scored" }));
  });
  u.items.forEach(function(p){
    p.measures.forEach(function(m){
      var a = splitTarget(m.target);
      rows.push(csvRow(PROG_COLS, { id:m.id, type:"MEASURE", parent_id:p.id, parent_name:p.name,
        name:m.name, direction:m.dir, value:a.value, unit:a.unit, compile:m.compile,
        current:m.actual, new_value:"",
        notes:m.target ? (m.horizon ? "measured at " + m.horizon : "")
                       : "no target set \u2014 recorded, not scored" }));
    });
    p.tactics.forEach(function(t){
      var pl = tacticPlanned(t);
      rows.push(csvRow(PROG_COLS, { id:t.id, type:"TACTIC", parent_id:p.id, parent_name:p.name,
        name:t.name, value:(pl == null ? "" : pl), unit:"%",
        current:t.actual, new_value:"",
        notes:tacticDue(t) ? "" : "not yet due \u2014 " + spanLabel(t) }));
    });
  });
  return rows.join("\n");
}

/* A parser that understands quoted fields, because a measure called
   "Revenue, gross" would otherwise split into two columns. */
function parseCSV(text){
  var rows = [], row = [], cur = "", q = false;
  text = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  for (var i = 0; i < text.length; i++) {
    var ch = text[i];
    if (q) {
      if (ch === '"' && text[i+1] === '"') { cur += '"'; i++; }
      else if (ch === '"') q = false;
      else cur += ch;
    } else if (ch === '"') q = true;
    else if (ch === ",") { row.push(cur); cur = ""; }
    else if (ch === "\n") { row.push(cur); rows.push(row); row = []; cur = ""; }
    else cur += ch;
  }
  if (cur !== "" || row.length) { row.push(cur); rows.push(row); }
  if (!rows.length) return [];
  var head = rows.shift().map(function(h){ return h.trim(); });
  return rows.filter(function(r){ return r.join("").trim() !== ""; })
             .map(function(r){
    var o = {};
    head.forEach(function(h, j){ o[h] = (r[j] == null ? "" : r[j]).trim(); });
    return o;
  });
}

/* ── Diff ─────────────────────────────────────────────────────────────────
   Nothing is applied on arrival. The upload is compared against what is
   recorded and the differences are put in front of the SMO. */

/* ── Validation ───────────────────────────────────────────────────────────
   Bad data that loads silently is worse than a file that refuses to load. A
   pillar with a theme code that does not exist is created, renders nowhere,
   and is found three months later by someone wondering why a theme is short.
   Problems block the apply; notices do not.
   ──────────────────────────────────────────────────────────────────────── */
/* Two checks before anything row-level: is this file for THIS unit, and is it
   the kind of template the toggle says. Every id carries its unit's key, so a
   file for the wrong unit announces itself \u2014 applying one would duplicate a
   whole plan into the wrong unit under foreign ids, which is the worst
   plausible import accident. And a progress file under kind=Plan quietly reads
   as a near-empty diff, which looks like an answer while being the wrong
   question. */
function checkFileShape(u, rows, kind){
  var problems = [];
  var foreign = {}, own = 0;
  rows.forEach(function(r){
    if (!r.id) return;
    var m = /^([a-z0-9]+)-/i.exec(r.id);
    if (!m) return;
    if (m[1] === u.ukey) own++;
    else if (UNITS[m[1]]) foreign[m[1]] = (foreign[m[1]] || 0) + 1;
  });
  var fk = Object.keys(foreign);
  if (fk.length && fk.reduce(function(a, k){ return a + foreign[k]; }, 0) > own) {
    var worst = fk.sort(function(a, b){ return foreign[b] - foreign[a]; })[0];
    problems.push({ at: "the whole file",
      msg: "this looks like " + UNITS[worst].name + "'s file \u2014 " + foreign[worst] +
           " rows carry its ids, and " + u.name + " is selected. Switch the unit above, or download " +
           u.name + "'s own template." });
  }
  var hasNewValue = rows.some(function(r){ return r.new_value != null && r.new_value !== undefined; });
  var hasPlanTypes = rows.some(function(r){ return ["PILLAR","FOUNDATION","ASPIRATION"].indexOf(r.type) > -1; });
  if (kind === "plan" && hasNewValue && !hasPlanTypes)
    problems.push({ at: "the whole file",
      msg: "this is a PROGRESS file \u2014 it carries new_value columns and no plan rows. Switch the toggle above to Progress." });
  if (kind === "progress" && hasPlanTypes)
    problems.push({ at: "the whole file",
      msg: "this is a PLAN file \u2014 it carries pillars and foundation rows, not reported values. Switch the toggle above to Plan." });
  return problems;
}

function validatePlan(u, rows){
  var problems = checkFileShape(u, rows, "plan"), notices = [], seen = {};
  var themes = GROUP.themes.map(function(x){ return x.ab; });
  var ids = {};
  rows.forEach(function(r){ if (r.id) ids[r.id] = true; });

  rows.forEach(function(r, n){
    var at = "row " + (n + 2) + (r.name ? " \u2014 " + r.name : "");
    if (!r.id)   { problems.push({ at:at, msg:"no id" }); return; }
    if (!r.type) { problems.push({ at:at, msg:"no type" }); return; }
    if (seen[r.id]) problems.push({ at:at, msg:"id " + r.id + " appears more than once" });
    seen[r.id] = true;

    if (r.type === "PILLAR") {
      if (r.theme && themes.indexOf(r.theme) < 0)
        problems.push({ at:at, msg:'theme "' + r.theme + '" is not one of ' + themes.join(", ") });
      var k = r.kind || kindFromNotes(r.notes);
      if (k && ["Direction","Capability"].indexOf(k) < 0)
        problems.push({ at:at, msg:'kind "' + k + '" is not Direction or Capability' });
      if (!r.theme) notices.push({ at:at, msg:"no theme \u2014 will read as cross-cutting" });
    }
    if (r.type === "MEASURE" || r.type === "TACTIC") {
      if (!r.parent_id) problems.push({ at:at, msg:"its pillar could not be matched \u2014 check the Pillar column" });
      else if (!ids[r.parent_id] && !findById(u, r.parent_id))
        problems.push({ at:at, msg:"parent_id " + r.parent_id + " matches no pillar" });
    }
    if (r.direction && ["\u2265","\u2264",">=","<="].indexOf(r.direction) < 0)
      problems.push({ at:at, msg:'direction "' + r.direction + '" is not \u2265 or \u2264' });
    if (r.compile && ["Sum","Latest","Average"].indexOf(r.compile) < 0)
      problems.push({ at:at, msg:'compile "' + r.compile + '" is not Sum, Latest or Average' });
    if (r.type === "TACTIC") {
      ["q1","q2","q3","q4"].forEach(function(q){
        if (r[q] !== "" && r[q] != null && ["0","1"].indexOf(String(r[q])) < 0)
          problems.push({ at:at, msg:q + ' is "' + r[q] + '", not 0 or 1' });
      });
      if (["q1","q2","q3","q4"].every(function(q){ return !+r[q]; }))
        notices.push({ at:at, msg:"no quarters marked \u2014 will never be due" });
    }
    if ((r.type === "MEASURE" || r.type === "NORTHSTAR") && !r.value)
      notices.push({ at:at, msg:"no target \u2014 recorded, not scored" });
  });
  return { problems:problems, notices:notices };
}

function kindFromNotes(notes){
  if (!notes) return "";
  if (/capabilit/i.test(notes)) return "Capability";
  if (/direction/i.test(notes)) return "Direction";
  return "";
}

function diffPlan(u, rows){
  var out = [], seen = {};

  /* The deck-extraction file carries the foundation as ONE row with the six
     clauses pipe-separated in source order, because that is how the slide
     reads. Both shapes are accepted: a single piped row is expanded against
     the unit's existing labels, six rows are taken as they come. */
  var expanded = [];
  rows.forEach(function(r){
    if (r.type === "FOUNDATION" && (r.description || "").indexOf("|") > -1) {
      (r.description).split("|").forEach(function(part, i){
        var c = u.clauses[i];
        if (!c) return;
        var txt = part.trim();
        /* The clause label is repeated at the head of each piped part in the
           source; strip it so the label is not swallowed into the text. */
        if (txt.toLowerCase().indexOf(c[0].toLowerCase()) === 0) txt = txt.slice(c[0].length).trim();
        expanded.push({ id:c[2], type:"FOUNDATION", name:c[0], description:txt });
      });
      return;
    }
    /* The source file carries one pipe-separated `owners` column. The first
       name is the owner and the rest are collaborators, which is the shape the
       platform holds. Either column is accepted. */
    if (r.owners && !r.owner) {
      var who = r.owners.split("|").map(function(x){ return x.trim(); }).filter(Boolean);
      r.owner = who.shift() || "";
      r.collaborators = who.join("|");
    }
    expanded.push(r);
  });
  rows = expanded;
  rows.forEach(function(r){
    if (!r.id) return;
    seen[r.id] = true;
    var hit = findById(u, r.id);
    var changes = [];
    var cmp = function(label, was, now){
      now = now == null ? "" : String(now);
      was = was == null ? "" : String(was);
      if (now !== "" && now !== was) changes.push({ f:label, was:was, now:now });
    };
    if (!hit) { out.push({ id:r.id, type:r.type, name:r.name || r.description, status:"new", changes:[], raw:r }); return; }
    if (hit.kind === "ASPIRATION") {
      cmp(hit.which === "end" ? "end in mind" : "statement",
          hit.which === "end" ? hit.obj.endInMind : hit.obj.aspiration, r.description);
    }
    else if (hit.kind === "FOUNDATION") { cmp("label", hit.obj[0], r.name); cmp("text", hit.obj[1], r.description); }
    else if (hit.swot) { cmp("text", hit.obj.name, r.name); }
    else if (hit.kind === "OBJECTIVE") {
      cmp("name", hit.obj.name, r.name); cmp("direction", hit.obj.dir, r.direction);
      if (r.value_3y !== "" && targetChanged(hit.obj.target3y, r.value_3y, r.unit))
        changes.push({ f:"3-year", was:hit.obj.target3y || "", now:joinTarget(hit.obj.target3y, r.value_3y, r.unit) });
      if (r.value !== "" && targetChanged(hit.obj.target, r.value, r.unit))
        changes.push({ f:"this year", was:hit.obj.target || "", now:joinTarget(hit.obj.target, r.value, r.unit) });
      cmp("compile", hit.obj.compile, r.compile);
    } else if (hit.kind === "PILLAR") {
      cmp("name", hit.obj.name, r.name);
      /* The source deck encodes kind as prose in notes \u2014 "Direction 01". A real
         column wins where present; the note is read only as a fallback, so
         files written for slide extraction still load. */
      cmp("kind", hit.obj.kind, r.kind || kindFromNotes(r.notes));
      cmp("theme", hit.obj.theme, r.theme); cmp("owner", hit.obj.owner, r.owner);
    } else if (hit.kind === "MEASURE") {
      cmp("name", hit.obj.name, r.name); cmp("direction", hit.obj.dir, r.direction);
      if (r.value !== "" && targetChanged(hit.obj.target, r.value, r.unit))
        changes.push({ f:"target", was:hit.obj.target || "", now:joinTarget(hit.obj.target, r.value, r.unit) });
      cmp("compile", hit.obj.compile, r.compile);
    } else if (hit.kind === "TACTIC") {
      cmp("name", hit.obj.name, r.name); cmp("owner", hit.obj.owner, r.owner);
      cmp("collaborators", (hit.obj.collaborators || []).join("|"), r.collaborators);
      cmp("description", hit.obj.description, r.description);
      cmp("outcome", hit.obj.outcome, r.outcome);
      ["q1","q2","q3","q4"].forEach(function(q){
        if (r[q] !== "") cmp(q.toUpperCase(), hit.obj[q] ? 1 : 0, r[q]);
      });
    }
    out.push({ id:r.id, type:hit.kind,
               name:hit.kind === "ASPIRATION" ? (hit.which === "end" ? "End in mind" : "Winning Aspiration")
                                             : (hit.obj.name || hit.obj[0]),
               status:changes.length ? "changed" : "same", changes:changes, hit:hit, raw:r });
  });
  /* Anything the platform holds that the sheet omits is reported, never
     removed. A missing row is far more often an editing slip than a decision
     to delete a measure with reported history against it. */
  var missing = [];
  u.items.forEach(function(p){
    if (!seen[p.id]) missing.push({ id:p.id, type:"PILLAR", name:p.name });
    p.measures.forEach(function(m){ if (!seen[m.id]) missing.push({ id:m.id, type:"MEASURE", name:m.name }); });
    p.tactics.forEach(function(t){ if (!seen[t.id]) missing.push({ id:t.id, type:"TACTIC", name:t.name }); });
  });
  u.keyObjectives.forEach(function(m){ if (!seen[m.id]) missing.push({ id:m.id, type:"OBJECTIVE", name:m.name }); });
  return { rows:out, missing:missing };
}

function diffProgress(u, rows){
  var out = [];
  rows.forEach(function(r){
    if (!r.id || (r.new_value || "") === "") return;
    var hit = findById(u, r.id);
    if (!hit) { out.push({ id:r.id, name:r.name, status:"unknown" }); return; }
    if (["MEASURE","TACTIC","OBJECTIVE"].indexOf(hit.kind) < 0) return;
    var was = hit.kind === "TACTIC" ? hit.obj.actual + "%" : hit.obj.actual;
    var now = r.new_value;
    if (String(was) === String(now)) return;
    out.push({ id:r.id, type:hit.kind, name:hit.obj.name,
               pillar:hit.pillar ? hit.pillar.name : (r.parent_name || ""),
               was:was, now:now, status:"changed", hit:hit });
  });
  return { rows:out, missing:[] };
}

/* Rows the platform has never seen are created, not just reported. Without
   this an upload could only ever edit a plan that already existed, and the
   main use \u2014 loading a unit's plan for the first time \u2014 would import nothing.
   Pillars are created before their children, so a measure always finds its
   parent however the file is ordered. */
function createFromPlan(u, d){
  var news = d.rows.filter(function(r){ return r.status === "new"; });
  var order = { PILLAR:0, NORTHSTAR:1, MEASURE:2, TACTIC:2, STRENGTH:3, WEAKNESS:3,
                OPPORTUNITY:3, THREAT:3, FOUNDATION:3, ASPIRATION:3, PLAN:9 };
  news.sort(function(a, b){ return (order[a.type] == null ? 5 : order[a.type]) -
                                   (order[b.type] == null ? 5 : order[b.type]); });
  var made = 0;
  news.forEach(function(r){
    var x = r.raw; if (!x) return;
    var t3 = joinTarget("", x.value_3y, x.unit), t1 = joinTarget("", x.value, x.unit);
    if (x.type === "PILLAR") {
      u.items.push({ id:x.id, name:x.name, sub:"", kind:x.kind || kindFromNotes(x.notes) || "Direction",
        theme:x.theme || "", owner:x.owner || "", slide:x.source_slide, notes:x.notes,
        measures:[], tactics:[] });
      made++;
    } else if (x.type === "MEASURE") {
      var p = u.items.filter(function(y){ return y.id === x.parent_id; })[0];
      if (!p) return;
      p.measures.push({ id:x.id, name:x.name, dir:x.direction || "\u2265", target:t1,
        compile:x.compile || "Latest", actual:"", progress:null,
        slide:x.source_slide, horizon:x.horizon, notes:x.notes });
      made++;
    } else if (x.type === "TACTIC") {
      var p2 = u.items.filter(function(y){ return y.id === x.parent_id; })[0];
      if (!p2) return;
      var col = (x.collaborators || "").split("|").map(function(s){ return s.trim(); }).filter(Boolean);
      p2.tactics.push({ id:x.id, name:x.name, description:x.description, outcome:x.outcome,
        owner:x.owner || "", collaborators:col,
        q1:+x.q1 ? 1 : 0, q2:+x.q2 ? 1 : 0, q3:+x.q3 ? 1 : 0, q4:+x.q4 ? 1 : 0,
        /* A plan that has just been loaded has no progress against it. Zero
           would read as started-and-delivered-nothing, which is a false
           failure on the day a plan arrives \u2014 the same trap as clearing. */
        status:"Not started", actual:null, slide:x.source_slide, notes:x.notes });
      made++;
    } else if (x.type === "NORTHSTAR") {
      u.keyObjectives.push({ id:x.id, name:x.name, dir:x.direction || "\u2265",
        target3y:t3, target:t1, compile:x.compile || "Latest", actual:"", progress:null,
        slide:x.source_slide });
      made++;
    } else if (["STRENGTH","WEAKNESS","OPPORTUNITY","THREAT"].indexOf(x.type) > -1) {
      var key = { STRENGTH:"s", WEAKNESS:"w", OPPORTUNITY:"o", THREAT:"t" }[x.type];
      (u.swot[key] = u.swot[key] || []).push(x.name);
      made++;
    } else if (x.type === "FOUNDATION") {
      u.clauses.push([x.name, x.description, x.id]);
      made++;
    }
  });
  return made;
}

function applyPlan(u, d){
  createFromPlan(u, d);
  d.rows.forEach(function(r){
    if (!r.hit) return;
    var o = r.hit.obj, raw = r.raw;
    /* Provenance and free-text notes travel with the row whether or not
       anything else changed, so they survive the round trip. */
    if (raw && o && typeof o === "object" && !Array.isArray(o)) {
      if (raw.source_slide) o.slide = raw.source_slide;
      if (raw.notes != null && raw.notes !== "" && r.hit.kind !== "PILLAR") o.notes = raw.notes;
      if (raw.horizon && r.hit.kind === "MEASURE") o.horizon = raw.horizon;
    }
    if (!r.changes.length) return;
    r.changes.forEach(function(c){
      if (r.hit.kind === "ASPIRATION" && c.f === "statement")   o.aspiration = c.now;
      if (r.hit.kind === "ASPIRATION" && c.f === "end in mind")  o.endInMind = c.now;
      if (r.hit.swot && c.f === "text") { r.hit.swot.arr[r.hit.swot.idx] = c.now; return; }
      if (r.hit.kind === "FOUNDATION" && c.f === "label") o[0] = c.now;
      if (r.hit.kind === "FOUNDATION" && c.f === "text")  o[1] = c.now;
      if (c.f === "name" && r.hit.kind !== "ASPIRATION" && r.hit.kind !== "FOUNDATION") o.name = c.now;
      if (c.f === "collaborators") o.collaborators = c.now ? c.now.split("|") : [];
      if (c.f === "description")   o.description = c.now;
      if (c.f === "outcome")       o.outcome = c.now;
      if (/^Q[1-4]$/.test(c.f))    o["q" + c.f[1]] = +c.now ? 1 : 0;
      if (c.f === "direction")  o.dir = c.now;
      if (c.f === "3-year")     o.target3y = c.now;
      if (c.f === "this year" || c.f === "target") o.target = c.now;
      if (c.f === "compile")    o.compile = c.now;
      if (c.f === "kind")       o.kind = c.now;
      if (c.f === "theme")      o.theme = c.now;
      if (c.f === "owner")      o.owner = c.now;

    });
  });
}

function applyProgress(u, d){
  d.rows.forEach(function(r){
    if (!r.hit) return;
    if (r.hit.kind === "TACTIC") {
      var n = parseInt(String(r.now).replace("%",""), 10);
      if (!isNaN(n)) {
        r.hit.obj.actual = Math.max(0, Math.min(100, n));
        /* The status pill follows the number, or a row reads 100% delivered
           beside "WIP". Statuses the number cannot infer \u2014 Blocked, On hold \u2014
           are left alone unless the figure plainly contradicts them. */
        var o = r.hit.obj;
        if (o.actual >= 100) o.status = "Done";
        else if (o.actual > 0 && (o.status === "Not started" || o.status === "Done")) o.status = "WIP";
        else if (o.actual === 0 && o.status === "Done") o.status = "WIP";
      }
    } else if (r.hit.kind === "MEASURE" || r.hit.kind === "OBJECTIVE") {
      r.hit.obj.actual = r.now;
      /* Progress is what the actual implies against the target, so it is
         recomputed rather than typed into a sheet where it could disagree. */
      var t = parseFloat(String(r.hit.obj.target).replace(/[^0-9.]/g, ""));
      var a = parseFloat(String(r.now).replace(/[^0-9.]/g, ""));
      if (!isNaN(t) && !isNaN(a) && t !== 0) {
        var pct = r.hit.obj.dir === "\u2264" ? (t / a) * 100 : (a / t) * 100;
        r.hit.obj.progress = Math.max(0, Math.min(150, Math.round(pct)));
      }
    }
  });
}
