/* The door's routes and no other wear index.html's stylesheet — generated by
   scripts/sync-css.mjs into public/door.css and LINKED, never bundled (see
   that script for why). `body.ready` is what the gate's own CSS keys its
   entrance on: the frozen door set it once the session check answered, and
   here the server has already answered when the page is written, so the
   class is added in the same document. */
export default function DoorLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <link rel="stylesheet" href="/door.css" />
      {children}
      <script dangerouslySetInnerHTML={{ __html: 'document.body.classList.add("ready")' }} />
    </>
  );
}
