import "./landing.css";

/* The platform's routes wear the product's own stylesheets, verbatim (D4):
   public/platform.css, generated by scripts/sync-css.mjs and LINKED rather
   than bundled, so the browser parses the product's bytes as the product's
   own page does. landing.css is this group's own and is bundled. */
export default function PlatformLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <link rel="stylesheet" href="/platform.css" />
      {children}
    </>
  );
}
